name: Test Gleam - Erlang
description: Test your gleam code on erlang/otp
inputs:
  gleam_version:
    description: what gleam version to test against
    required: true
    default: "1"
  erlang_version:
    description: what erlang/otp version to test against
    required: true
    default: "26"

runs:
  using: composite
  steps:
    - uses: erlef/setup-beam@v1
      with:
        rebar3-version: 3
        otp-version: ${{ inputs.erlang_version }}
        gleam-version: ${{ inputs.gleam_version }}
    - run: gleam test --target erlang
      shell: bash
