name: Restore Gleam Deps Cache
description: restore cached gleam dependencies to avoid downloading them from hex

runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v4
      with:
        path: ./build/packages
        key: deps-${{ hashFiles('manifest.toml') }}
