name: Install gleam and erlang

description: Check that your gleam code is formatted properly

inputs:
  gleam_version:
    description: what gleam version to install
    required: true
    default: "1"
  erlang_version:
    description: what erlang/otp version to install
    required: true
    default: "26"

runs:
  using: composite
  steps:
    - uses: erlef/setup-beam@v1
      with:
        rebar3-version: 3
        otp-version: ${{ inputs.erlang_version }}
        gleam-version: ${{ inputs.gleam_version }}
