name: Gleam Publish

description: publish a gleam package to hex.pm

inputs:
  gleam_version:
    description: what gleam version to test against
    required: true
    default: "1"
  erlang_version:
    description: what erlang/otp version to test against
    required: true
    default: "26"
  hex_key:
    description: hex.pm API key
    required: false

runs:
  using: composite
  steps:
    - run: gleam publish -y
      env:
        HEXPM_API_KEY: ${{ inputs.hex_key }}
      shell: bash
