name: Cache and restore Gleam Deps

description: cache gleam dependencies for faster access later

runs:
  using: composite
  steps:
    - name: Check cache
      uses: actions/cache/restore@v4
      id: restore
      with:
        path: ./build/packages
        key: deps-${{ hashFiles('manifest.toml') }}
    - if: steps.restore.outputs.cache-hit != 'true'
      run: gleam deps download
      shell: bash
    - if: steps.restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ./build/packages
        key: deps-${{ hashFiles('manifest.toml') }}
