name: Test Gleam - Node
description: Test your gleam code on nodeJS
inputs:
  gleam_version:
    description: what gleam version to test against
    required: true
    default: "1"
  erlang_version:
    description: what erlang/otp version to test against
    required: true
    default: "26"
  node_version:
    description: what nodeJS version to test against
    required: true
    default: "20"

runs:
  using: composite
  steps:
    - uses: erlef/setup-beam@v1
      with:
        rebar3-version: 3
        otp-version: ${{ inputs.erlang_version }}
        gleam-version: ${{ inputs.gleam_version }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    - run: gleam test --target javascript
      shell: bash
