name: Test

on:
  workflow_call:
    inputs:
      gleam_version:
        type: string
        required: true
        default: "1"
      test_erlang:
        type: boolean
        default: true
      erlang_version:
        type: string
        default: "26"
      test_node:
        type: boolean
        default: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/install_gleam@main
        with:
          gleam_version: ${{inputs.gleam_version}}
          erlang_version: ${{inputs.erlang_version}}
      - uses: TanklesXL/gleam_actions/.github/actions/format@main

  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/install_gleam@main
        with:
          gleam_version: ${{ inputs.gleam_version }}
          erlang_version: ${{ inputs.erlang_version }}
      - uses: TanklesXL/gleam_actions/.github/actions/deps_cache@main

  test_erlang:
    if: inputs.test_erlang
    runs-on: ubuntu-latest
    needs: deps
    strategy:
      fail-fast: true
      matrix:
        erlang: ["28", "27"]
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/install_gleam@main
        with:
          gleam_version: ${{ inputs.gleam_version }}
          erlang_version: ${{ matrix.erlang }}
      - uses: TanklesXL/gleam_actions/.github/actions/deps_cache@main
      - uses: TanklesXL/gleam_actions/.github/actions/test@main
        with:
          target: "erlang"

  test_node:
    if: inputs.test_node
    runs-on: ubuntu-latest
    needs: deps
    strategy:
      fail-fast: true
      matrix:
        node: ["22", "20", "18"]
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/install_gleam@main
        with:
          gleam_version: ${{ inputs.gleam_version }}
          erlang_version: ${{ inputs.erlang_version }}
      - uses: TanklesXL/gleam_actions/.github/actions/deps_cache@main
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: TanklesXL/gleam_actions/.github/actions/test@main
        with:
          target: "javascript"
          install_node: "true"
          node_version: ${{ matrix.node }}
