name: Test

on:
  workflow_call:
    inputs:
      gleam_version:
        type: string
        required: true
      erlang_enabled:
        type: boolean
      node_enabled:
        type: boolean

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/format@main
        with:
          gleam_version: ${{ inputs.gleam_version }}

  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/deps_cache@main
        with:
          gleam_version: ${{ inputs.gleam_version }}

  test_erlang:
    if: inputs.erlang_enabled
    runs-on: ubuntu-latest
    needs: deps
    strategy:
      fail-fast: true
      matrix:
        erlang: ["26", "25", "27.0-rc3"]
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/deps_restore@main
      - uses: TanklesXL/gleam_actions/.github/actions/test_erlang@main
        with:
          erlang_version: ${{ matrix.erlang }}
          gleam_version: ${{ inputs.gleam_version }}

  test_node:
    if: inputs.node_enabled
    runs-on: ubuntu-latest
    needs: deps
    strategy:
      fail-fast: true
      matrix:
        node: ["22", "20", "18"]
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/deps_restore@main
      - uses: TanklesXL/gleam_actions/.github/actions/test_node@main
        with:
          node_version: ${{ matrix.node }}
          gleam_version: ${{ inputs.gleam_version }}
